---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: asgard-demo
  namespace: default
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/services-engineering/asgard-demo.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: asgard-demo
  namespace: default
spec:
  interval: 5m0s
  path: ./
  prune: true
  sourceRef:
    kind: GitRepository
    name: asgard-demo